### PR TITLE
Added TS typings

### PR DESCRIPTION
**Pull request by igorkamyshev**
Hello. I try to implement typings for TS. I can't achieve the better result. Please review my solutions and give me feedback.

What do you think?

### CODE REVIEW

**Comment by igorkamyshev** [comment]
I'm sorry. In TS 2.8 conditional types were added. Fix it.

**Comment by igorkamyshev** [comment]
@sergeysova, will you have time to see it this week?

**Comment by sergeysova** [comment]
@igorkamyshev what about tests for typings?

**Comment by sergeysova** [comment]
@igorkamyshev you don't typing action creator arguments types.

```ts
const { actions } = createSymbiote(initialState, {
  foo: {
    bar: (state, a: string, b: number) => ({ ...state })
  }
})

actions.foo.bar("foo", "2") // should broken
```

**Comment by igorkamyshev** [comment]
@sergeysova sure, I will write tests and returns later.

Actions must compatible with `Actions type` (second parameter for `createSymbiote` function). Do you think, automatically checking in potential? Please, share the article/docs about this TypeScript feature.

Thanks for review.

**Comment by sergeysova** [comment]
I merge it now. But wait for tests

**Comment by sergeysova** [comment]
@igorkamyshev Thank you!

**Comment by igorkamyshev** [comment]
@sergeysova okay, will fixed.

**Pull request merged**
